### ISSUE TITLE
Comparing two Guid (created with RT.Comb) if lower

### ISSUE THREAD

**Issue by pethopal** [richardtallent/RT.Comb#11]
In SQL server I can check two GUID if one is lower. (So if one is created before.)

I needed the same functionality in C# 
Do you have a suggestion how can I do that?

Thanks for advance,
 Best Regards, PP

**Comment by richardtallent** [comment]
Sure! Yes, C#'s native `System.Guid` type does not sort the same way as SQL Server's GUID. However, .NET does include a different type, `System.Data.DataTypes.SqlGuid`, that compares/sorts the same way as SQL Server, and it supports implicit conversion.

Here's a little utility extension method to use that data type to do the comparison:

```
public static int CompareToComb(this Guid comb1, Guid comb2)
    => ((SqlGuid)comb1).CompareTo((SqlGuid)comb2);
```

You can use this method as you would the native `Guid.CompareTo()` method, including passing it as a delegate to sort a list of COMB values.

You could also create an extension method like this, which more clearly identifies the intent of the comparison:

```
public static bool DateIsAfter(this Guid comb1, Guid comb2)
    => ((SqlGuid)comb1).CompareTo((SqlGuid)comb2) > 0;
```

Hope that helps!
