### ISSUE TITLE
Installing NuGet package pulls in lots of unwanted "dependencies"

### ISSUE THREAD

**Issue by sjmorgan81** [richardtallent/RT.Comb#13]
My project is targeting .NET Framework 4.6.1 and when I go to install RT.Comb 2.3.0 I get the following prompt to install a load of dependencies for code that's already part of the .NET standard library:

![image](https://user-images.githubusercontent.com/38432155/64010665-26a97380-cb12-11e9-98e9-6ffb0a9a4bbc.png)

I think this issue might be fixable by either bumping the version of .NET Standard you target to 2.0 (I'm using Dapper which targets 2.0 and don't have this issue) or adding another entry to `<TargetFrameworks>` as discussed [here](http://blog.tdwright.co.uk/2017/11/21/update-getting-net-standard-apps-playing-nicely-on-nuget/).

**Comment by richardtallent** [comment]
I think you're right. I haven't had a chance to look at this, but I will be moving it to .NET Standard 2.0 soon. I use Dapper as well, and I have projects targeting both .NET Core and .NET 4.7.2 using this library.

**Comment by richardtallent** [comment]
The library targets .NET Standard 2.0, and the tests and other command-line tools now target .NET 5.0, so this should no longer be an issue. Thanks!
