### ISSUE TITLE
Generate Guid for a specific DateTime (i.e. not for Now)

### ISSUE THREAD

**Issue by pethopal** [richardtallent/RT.Comb#14]
Hi, I used RT.Comb succesfully many years. (In SQL Server these Guids can even be used as Primary Keys)

For efficient querying purposes can I generate a Guid for a Specific DateTime. 
(Note I will use it for only in SQL Where '>', '<' clause.

Thanks...

**Comment by richardtallent** [comment]
That's great to hear! I use them for PKs in a number of projects as well in MSSQL / AzureDB projects.

You can query for COMBs falling within a date range. If your SQL is being dynamically generated from .NET code, you can just create the boundary COMBs for your query parameters like this (untested):

```C#
var fromComb = provider.Create(Guid.Empty, startDateTime);
var toComb = provider.Create(new Guid("FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF", endDateTime);
```

If you're looking to convert from a date range to a COMB query directly in T-SQL (for example, feeding `datetime` values to a stored procedure and having it search on the COMB values), you can use the T-SQL examples shown in the README for your chosen provider to combine the "empty" and "full" GUID values with your start and end `datetime` values, respectively.

Either way, you'll be able to take full advantage of indexing. It's not as efficient as a "real" datetime column and index, of course, but it's fine for a wide range of use cases.
