### ISSUE TITLE
check whether a Guid is an RT.Comb one

### ISSUE THREAD

**Issue by pethopal** [richardtallent/RT.Comb#19]
Hi Richard,
 I have been using for the RT.Comb GUIDs very successfully both in OLTP, and OLAP projects.

All the time these GUIDs were generated by us, I mean, at our side: so we were sure that these are ordered.

But now I will be dependent on an outer application.
The question is whether I can check/test whether this GUID is RT.Comb one? 
(If it will not be the case, I will substitute this with an RT.Comb one, so at the database side everything will be ordered.)

Thanks in advance,
 Pál

**Comment by richardtallent** [comment]
Hi Pál,

I'm glad to hear it!

To test, you can look for GUIDs outside your expected date range:

```SQL

SELECT * FROM myTable WHERE 
guid < SELECT CAST(
    CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', '2015-01-22') AS BINARY(16))
    AS UNIQUEIDENTIFIER)
OR guid > SET @startGuid = SELECT CAST(
    CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', GETUTCDATE()) AS BINARY(16))
    AS UNIQUEIDENTIFIER);
```

The above code assumes that you started using COMBs on 2015-01-22 and that you are using the `UnixTimeStampStrategy` with `SqlCombProvider` on MSSQL 2016+ or Azure DB. The same approach can be used with the other strategies or database platforms. 

This is not foolproof -- there is a small but real chance that a random non-COMB GUID may have a "valid" COMB date/time. If you have other data you can compare to -- for example, an audit log of when the record was inserted -- you could look for a smaller valid date range.

I'm looking at doing the same thing with some legacy data. In my case, the GUIDs were created using the original `SqlDateTimeStrategy` and I've now standardized my code to use the `UnixTimeStampStrategy`. So in my case I'll be looking for GUIDs outside the acceptable Unix date range but within the SQL DateTime range, extracting the timestamp, and re-creating the equivalent Unix timestamp GUID. I haven't written the code for that yet, but it'll be similar to the above. Fortunately, none of the GUIDs in my case are used as foreign keys, so this should be a fairly simple process.

**Comment by pethopal** [comment]
Hi Richard,
 thanks for the check code, info!
