### ISSUE TITLE
Full comb from timestamp

### ISSUE THREAD

**Issue by ISV-Kran** [richardtallent/RT.Comb#24]
Hi, newbie question here.

I'm wondering if it's possible to convert a timestamp to the exact original comb guid.

```
SqlCombProvider provider = new(new UnixDateTimeStrategy(), new UtcNoRepeatTimestampProvider().GetTimestamp);

Guid comb = provider.Create();
DateTime timestamp = provider.GetTimestamp(comb);
Guid comb1 = provider.Create(timestamp);
Guid comb2 = provider.Create(comb, timestamp);

Console.WriteLine(comb.Equals(comb1)); // false
Console.WriteLine(comb.Equals(comb2)); // true, but possible only from timestamp?
```

If I understand correctly, documentation explain that first bytes of guid is random. There is a way to obtain the original full comb id only from timestamp?

Thank you so much.

**Comment by richardtallent** [comment]
The GUID contains 128 bits of information, the timestamp contains only 48. So so, the timestamp along cannot predict the COMB value, there are 2^80 random variation possibilities for every millisecond.

You can, however, extract the timestamp from the COMB. It's not terribly efficient, so I wouldn't do that in the normal course of events, but it is a handy side-effect.

And if you have the timestamp, you can search for the *range* of COMB values that *could* have been generated during that timestamp, by simply searching for COMB values >= a COMB generated from a GUID with all 0's and that timestamp and a GUID with all 1's (talking binary here, not hex). But if there are multiple COMBs generated during that timestamp, you won't be able to distinguish them from the timestamp.
