### ISSUE TITLE
Question about existing SQL Server Tables

### ISSUE THREAD

**Issue by GioviQ** [richardtallent/RT.Comb#25]
Hi, after reading https://davecallan.com/generating-sequential-guids-which-sort-sql-server-in-net/

I would like to introduce in my SQL Server tables Id generated as sequential Guid.

I just have applications in production with populated tables and normal Guid IDs, may I have any issue?

**Comment by richardtallent** [comment]
No issues should be expected, other than:

- If the GUID is the clustered key, INSERT statements won't *necessarily* be at the end of the table, like they would be if you had started with COMB GUIDs.
- You can't "decode" a useful timestamp from the old GUIDs.
