### ISSUE TITLE
M.E.DependencyInjection v7.0 potentially breaks .NET 6.0 apps/sites

### ISSUE THREAD

**Issue by fubar-coder** [richardtallent/RT.Comb#26]
# Proposal

Please change the dependency on M.E.DependencyInjection v7.0 to v6.0 for `RT.Comb.AspNetCore` v4.0.

# Reasoning

All the .NET 6.0 stuff (e.g. ASP.NET Core 6.0) relies on M.E.DependencyInjection v6.0 and using NuGet packages shipped alongside with .NET 7.0 seems like a potentially dangerous move, because nobody can guarantee that the interface surface didn't change between v6.0 and v7.0.

**Comment by richardtallent** [comment]
Makes sense, addressed in 4.0.1. There's nothing in here specific to v7 of that package.
