### ISSUE TITLE
Suggestion for T-SQL query to use SYSUTCDATETIME() instead of GETUTCDATE()

### ISSUE THREAD

**Issue by Reikooters** [richardtallent/RT.Comb#29]
## Using SYSUTCDATETIME() instead of GETUTCDATE()

First of all, thank you for creating the library.

The readme has the following examples for generating a COMB in T-SQL

> Creating a COMB uniqueidentifier in T-SQL with the current date and time:
> ```sql
> DECLARE @now DATETIME = GETUTCDATE();
> DECLARE @daysSinceEpoch BIGINT = DATEDIFF(DAY, '1970-1-1', @now);
> DECLARE @msLeftOver INT = DATEDIFF(MILLISECOND, DATEADD(DAY, @daysSinceEpoch, '1970-1-1'), @now);
> SELECT CAST(
>         CAST(NEWID() AS BINARY(10))
>         + CAST(@daysSinceEpoch * 24 * 60 * 60 * 1000 + @msLeftOver AS BINARY(6))
>     AS UNIQUEIDENTIFIER);
> ```
> Or on MSSQL 2016/Azure:
> ```sql
> SELECT CAST(
>         CAST(NEWID() AS BINARY(10))
>         + CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', GETUTCDATE())
>     AS BINARY(6)) AS UNIQUEIDENTIFIER);
> ```

These use `GETUTCDATE()` which returns a `datetime` with 1/300s precision.

Instead use `SYSUTCDATETIME()` which returns a `datetime2(7)` which for this purpose will give you 1/1000s precision as per what you would get with the `UnixDateTimeStrategy` in C#.

`datetime2` and `SYSUTCDATETIME()` were introduced in SQL Server 2008 so is usable in both above examples.

Suggested change:

> Creating a COMB uniqueidentifier in T-SQL with the current date and time:
> ```sql
> DECLARE @now DATETIME2(7) = SYSUTCDATETIME();
> DECLARE @daysSinceEpoch BIGINT = DATEDIFF(DAY, '1970-1-1', @now);
> DECLARE @msLeftOver INT = DATEDIFF(MILLISECOND, DATEADD(DAY, @daysSinceEpoch, '1970-1-1'), @now);
> SELECT CAST(
>         CAST(NEWID() AS BINARY(10))
>         + CAST(@daysSinceEpoch * 24 * 60 * 60 * 1000 + @msLeftOver AS BINARY(6))
>     AS UNIQUEIDENTIFIER);
> ```
> Or on MSSQL 2016/Azure:
> ```sql
> SELECT CAST(
>         CAST(NEWID() AS BINARY(10))
>         + CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', SYSUTCDATETIME())
>     AS BINARY(6)) AS UNIQUEIDENTIFIER);
> ```

## UDF to generate a COMB

The below is separate but I'd also like to contribute a user defined function that I use to make queries simpler to read, at the performance cost of the overhead of calling a function. Don't have to add it to the readme.
```sql
/****** Object:  UserDefinedFunction [dbo].[NewComb] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Description:    Return a COMB GUID (sortable uniqueidentifier). See https://github.com/richardtallent/RT.Comb
-- =============================================
CREATE FUNCTION [dbo].[NewComb]()
RETURNS uniqueidentifier
AS
BEGIN
    -- Generate a COMB as per https://github.com/richardtallent/RT.Comb documentation
    RETURN CAST(
        CAST((select new_id from vwGetNewID) AS BINARY(10))
        + CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', SYSUTCDATETIME())
    AS BINARY(6)) AS UNIQUEIDENTIFIER);
END
GO

/****** Object:  UserDefinedFunction [dbo].[NewCombFromDateTime] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Description:    Return a COMB GUID (sortable uniqueidentifier). See https://github.com/richardtallent/RT.Comb
-- =============================================
CREATE FUNCTION [dbo].[NewCombFromDateTime]
(
    @datetime datetime2(3)
)
RETURNS uniqueidentifier
AS
BEGIN
    -- Generate a COMB as per https://github.com/richardtallent/RT.Comb documentation
    RETURN CAST(
        CAST((select new_id from vwGetNewID) AS BINARY(10))
        + CAST(DATEDIFF_BIG(MILLISECOND, '1970-1-1', @datetime)
    AS BINARY(6)) AS UNIQUEIDENTIFIER);
END
GO

/****** Object:  View [dbo].[vwGetNewID] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Description:    View which returns newid()
-- =============================================
CREATE VIEW [dbo].[vwGetNewID] AS SELECT newid() AS new_id
GO
```
The above script creates two user defined functions (UDFs), `NewComb` which uses the current time, and `NewCombFromDateTime` which takes the date/time as a parameter. These return a COMB.

Usable like so:

```sql
-- Generate a COMB with the current utc date/time
select dbo.NewComb()

-- or:

-- Generate a COMB with a given utc date/time
declare @now datetime2(3) = sysucdatetime()

select dbo.NewCombFromDateTime(@now)
```

Note that the script above also creates a view named `vwGetNewID` which returns `newid()`. This is a hack to allow the use of `newid()` in a UDF which isn't allowed normally. Alternatively, you could eliminate the view but would need to add a `uniqueidentifier` parameter in which you pass `newid()` as a parameter to the function so that it has a guid to work with.

**Comment by richardtallent** [comment]
Great idea! I've been running procedures like the above (including the view hack) for many years (in the default constraints for my COMB-keyed tables, for example), but O didn't think to actually include them as separate SQL scripts. I've added those, based on a combination of the production code from one of my apps and the code above.

I chose not to include functions for generating a COMB for a parameterized date/time. That's something someone can do on their own if they need that sort of thing for testing, but in real-world use, it's best to just use the database server's clock, unless you're generating the whole COMB in .NET code.
